export const navItemsData = [
  {
    text: "Home.",
    isOpen: true,
    href: "#home",
    imgSrc: "/imgs/samples/sample2.jpg",
    imgSizes: "",
    imgSrcSet: "",
  },
  {
    text: "About us.",
    isOpen: true,
    href: "#about",
    imgSrc: "/imgs/samples/sample3.jpg",
    imgSizes: "",
    imgSrcSet: "",
  },
  {
    text: "New collection.",
    isOpen: true,
    href: "#collection",
    imgSrc: "/imgs/samples/sample5.jpg",
    imgSizes: "",
    imgSrcSet: "",
  },
  {
    text: "Our products.",
    isOpen: true,
    href: "#products",
    imgSrc: "/imgs/samples/sample4.jpg",
    imgSizes: "",
    imgSrcSet: "",
  },
  {
    text: "Reviews.",
    isOpen: false,
    href: "",
    imgSrc: "/imgs/samples/sample6.jpg",
    imgSizes: "",
    imgSrcSet: "",
  },
];
